name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check formatting
        run: npm run fmt:check
      
      - name: Lint
        run: npm run lint
      
      - name: Verify package-lock.json is committed
        run: |
          if git ls-files --error-unmatch package-lock.json > /dev/null 2>&1; then
            echo "package-lock.json is properly committed to the repository."
          else
            echo "ERROR: package-lock.json is not committed to the repository."
            echo "Please run 'npm install' and commit the package-lock.json file."
            exit 1
          fi
      
      - name: Verify all CI checks pass
        run: echo "All checks passed!" 